<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sitepackage"
 *
 * Auto generated by Extension Builder 2015-12-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Site Package tophair.de',
	'description' => 'Configuration of tophair.de',
	'category' => 'templates',
	'author' => 'tf',
	'author_email' => 'feuerstein.rhp@gmail.com',
	'author_company' => 'RHEINPFALZ Verlag und Druckerei GmbH & Co. KG',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.5.0-7.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>